analysis/core/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'analysis.core.views',
    url(r'^database/$', 'manage_databases', name='databases'),
    url(r'^database/create$', 'create_database', name='create_database'),
    url(r'^database/(\d+)/edit$', 'create_database', name='edit_database'),
    url(r'^database/(\d+)/delete$', 'delete_database', name='delete_database'),
    url(r'^database/(\d+)/group$', 'manage_database_group', name='manage_database_group'),

    url(r'^views/$', 'manage_views', name='views'),
    url(r'^views/create$', 'create_report', name='create_view'),
    url(r'^views/(\d+)/edit$', 'create_report', name='edit_view'),
    url(r'^views/(\d+)/delete$', 'delete_view', name='delete_view'),

    url(r'^database/tables$', 'list_tables', name='query_tables'),
    url(r'^database/db_groups/$', 'list_database_groups', name='query_db_groups'),


    url(r'^database/get_sample_data$', 'show_sample_data', name='get_sample_data'),
)

analysis/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', 'analysis.dashboard.views.home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('analysis.account.urls')),

    url(r'^dashboard/collection/', include('analysis.collection.urls')),
    url(r'^dashboard/', include('analysis.dashboard.urls')),

    url(r'^manage/', include('analysis.dip.urls')),
    url(r'^manage/aggregate/', include('analysis.aggregate.urls')),
    url(r'^manage/', include('analysis.core.urls')),
)

analysis/account/models.py
# coding: utf8
from django.contrib.auth.models import User, Group
from django.db import models


class GroupAdminManager(models.Manager):
    def is_admin(self, group, user):
        return self.filter(group=group, user=user).exists()


class GroupAdmin(models.Model):
    user = models.ForeignKey(User, related_name="admin_groups")
    group = models.ForeignKey(Group, related_name="admins")

    objects = GroupAdminManager()


class GroupRequestStatus:
    NEW = 1
    APPROVE = 2
    REJECT = 3


class GroupAddRequest(models.Model):
    user = models.ForeignKey(User, verbose_name="申请人")
    group = models.ForeignKey(Group)
    status = models.SmallIntegerField(default=GroupRequestStatus.NEW)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return "%s :%s :%s" % (
            self.user,
            self.group,
            self.status,
        )

    def audit(self):
        self.status = GroupRequestStatus.NEW
        self.save()

    def approve(self):
        self.status = GroupRequestStatus.APPROVE
        self.save()

    def reject(self):
        self.status = GroupRequestStatus.REJECT
        self.save()

analysis/core/models.py
# coding: utf8
from __future__ import unicode_literals
import MySQLdb

from django.contrib.auth.models import User, Group
from django.db import models
from django.utils import timezone


ENGINE_CHOICES = (
    ('MySQL', 'mysql'),
)


class DatabaseManager(models.Manager):
    pass


class Database(models.Model):
    creator = models.ForeignKey(User, related_name='dbs')

    engine = models.CharField('类型', max_length=100, choices=ENGINE_CHOICES)
    host = models.CharField('主机', max_length=100,
                            help_text="尽量填可以通过外部访问的IP/域名，不要填 localhost")
    port = models.PositiveIntegerField('端口', default=3306)
    name = models.CharField('数据库', max_length=100)
    user = models.CharField('用户名', max_length=100)
    password = models.CharField('密码', max_length=100, blank=True)

    groups = models.ManyToManyField(Group, db_constraint=False, related_name='databases')

    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        pass

    def stringify(self):
        return '%s://%s:%s@%s:%s/%s' % (
            self.engine, self.user, self.password, self.host, self.port, self.name
        )

    def __unicode__(self):
        return "%s://%s@%s:%s/%s" % (
            self.engine,
            self.user,
            self.host,
            self.port,
            self.name
        )

    def connect(self):
        return MySQLdb.connect(
            host=self.host, port=self.port, db=self.name,
            user=self.user, passwd=self.password,
            charset='utf8')


class Report(models.Model):
    creator = models.ForeignKey(User, verbose_name='创建人')
    name = models.CharField('报告名字', max_length=100)

    database = models.ForeignKey(Database, verbose_name='数据库',
                                 related_name='reports')
    table = models.CharField('表', max_length=100)

    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        verbose_name = "数据报表"

    def __unicode__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return 'dashboard_report', [self.id]


class FieldType:
    DIMENSION = 1
    PROPERTY = 2


class Field(models.Model):
    """
    数据报表的字段

    source
        表中的字段，如果是指标则可以包括多个字段，
        包括多个字段时使用 expression 计算最终值

    type 指定是维度还是指标
    data_type 是指标的类型 (size, time, number, percent)
    expression 指标的计算规则
    """
    report = models.ForeignKey(Report, verbose_name='报告',
                               related_name="fields")
    order = models.SmallIntegerField('字段顺序')

    type = models.SmallIntegerField('字段类型', choices=(
        (FieldType.DIMENSION, '维度'),
        (FieldType.PROPERTY, '指标'),
    ))

    source = models.CharField('表字段', max_length=100)
    display = models.CharField('显示名称', max_length=100)

    data_type = models.CharField('数据类型', max_length=20, null=True, blank=True)
    expression = models.CharField('表达式', null=True, blank=True, max_length=200)

    class Meta:
        ordering = ['order']

    def __unicode__(self):
        return self.display

    def type_string(self):
        if self.type == FieldType.DIMENSION:
            return 'dimension'
        elif self.type == FieldType.PROPERTY:
            return 'property'
        return 'ignore'

analysis/core/forms.py
from _mysql import OperationalError
from django import forms
# from django.db import OperationalError
from django.contrib.auth.models import Group
from analysis.core.models import Database, Report
import MySQLdb


class DatabaseForm(forms.ModelForm):

    class Meta:
        model = Database
        fields = ('host', 'port', 'name', 'user', 'password')

        widgets = {
            'password': forms.PasswordInput(),
        }

    def clean(self):
        values = dict(self.cleaned_data.items())
        values.update({
            'passwd': values.get('password', ''),
            'db': values['name']
        })

        del values['name']
        if 'password' in values:
            del values['password']

        try:
            MySQLdb.connect(**values)
        except OperationalError, e:
            raise forms.ValidationError(e)

        return self.cleaned_data


class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ('name', 'database', 'table')

class DbGroupForm(forms.ModelForm):

    class Meta:
        model = Database
        fields = ('name', 'groups')
        widgets = {'name': forms.HiddenInput()}

    groups = forms.ModelMultipleChoiceField(queryset=Group.objects.all(),
                                            widget=forms.CheckboxSelectMultiple,
                                            required=False)

analysis/core/views.py
# coding: utf8
from __future__ import unicode_literals

from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.core.urlresolvers import reverse
from django.db import transaction
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from analysis.core.forms import DatabaseForm, ReportForm, DbGroupForm

from analysis.core.models import Database, Report, Field
from analysis.core.utils import render_json


@login_required
def manage_databases(request):
    context = {
        'databases': Database.objects.all().select_related('group'),
        'groups': Group.objects.all()
    }
    return render(request, 'core/manage_databases.html', context)


@login_required
def create_database(request, db_id=None):
    origin_instance = get_object_or_404(Database, id=db_id) if db_id else None

    if request.method == 'POST':
        form = DatabaseForm(request.POST, instance=origin_instance)
        group_ids = request.POST.getlist('groups')

        if form.is_valid():

            db = form.save(commit=False)
            if not db.pk:
                db.engine = 'mysql'
                db.creator = request.user

            db.save()
            db.groups = Group.objects.filter(id__in=group_ids)
            db.save()

            return redirect(reverse('databases'))

    else:
        form = DatabaseForm(instance=origin_instance)

    return render(request, "core/create_database.html", {'form': form, 'all_groups': Group.objects.all()})



@staff_member_required
def list_tables(request):
    db_id = request.GET.get('database')
    db = get_object_or_404(Database, id=db_id)

    conn = db.connect()
    cursor = conn.cursor()
    cursor.execute('show tables;')

    result = []

    for table in cursor.fetchall():
        table = table[0]
        cursor.execute('show columns from `%s`' % table)

        result.append({
            'name': table,
            'fields': [{'name': row[0].strip(), 'type': row[1]} for row in cursor]
        })

    return render_json(result)


@staff_member_required
def list_database_groups(request):
    db_id = request.GET.get('db')
    db = get_object_or_404(Database, id=db_id)
    result = []

    result.append({
        'db_id':db_id,
        'all_groups':db.groups.all(),
        'added_groups_list':list(db.groups.all())
    })
    return render_json(result)


@staff_member_required
def create_report(request, report_id=None):
    """
    创建报表
    :param report_id: 如果不为 None 则是编辑报表
    """
    if not Database.objects.count():
        messages.error(request, "还没有创建数据库哦，无法创建报表")
        return redirect(reverse('databases'))

    instance = get_object_or_404(Report, id=report_id) if report_id else None

    if request.method == 'POST':
        form = ReportForm(request.POST, instance=instance)

        if form.is_valid():
            with transaction.atomic():
                report = form.save(commit=False)
                if not report.pk:
                    report.creator = request.user

                report.save()

                # delete old dimensions
                report.fields.all().delete()

                field_count = request.POST.get('field_count', '0')
                types = ['dimension', 'property']

                for x in xrange(int(field_count)):
                    fields = ['display', 'source', 'type', 'data_type', 'expression']
                    display, source, type, data_type, express = [
                        request.POST.get("field_%d_%s" % (x, f)) or '' for f in fields]

                    if not type in types:
                        continue

                    Field.objects.create(
                        report=report,
                        order=x,
                        type=types.index(type) + 1,
                        source=source.strip(),
                        display=display,
                        data_type=data_type,
                        expression=express.strip(),
                    )

            messages.success(request, "数据报表创建成功")
            return redirect(reverse('views'))

    else:
        form = ReportForm(instance=instance, initial={
            # 'database': Database.objects.get(id=request.GET.get('db'))
            'database': request.GET.get('db')
        })

    context = {
        'report': instance,
        'form': form
    }
    return render(request, "core/create_view.html", context)


@staff_member_required
def manage_views(request):
    context = {
        'reports': Report.objects.all(),
    }
    return render(request, "core/manage_views.html", context)

@require_POST
@staff_member_required
def delete_view(request, view_id=None):
    report = get_object_or_404(Report, id=view_id)

    report.delete()

    messages.success(request, "报表已删除")
    return redirect(reverse('views'))

@require_POST
@staff_member_required
def delete_database(request, database_id=None):
    database = get_object_or_404(Database, id=database_id)

    if database.reports.count()>0:
        messages.error(request, "请先删除数据库中的表，再删除数据库。")
    else:
        database.delete()
        messages.success(request, "数据库已删除")
    return redirect(reverse('databases'))


@staff_member_required
def manage_database_group(request, database_id=None):
    database_instance = get_object_or_404(Database, id=database_id)

    if request.method == 'POST':
        form = DbGroupForm(request.POST, instance=database_instance)
        if form.is_valid():
            db = form.save()
            db.save()
            messages.success(request, "数据库的用户组改变成功")

        else:
            for (k, v) in form.errors.items():
                messages.error(request, "存在错误%s : %s" % (k, v))
    else:
        form = DbGroupForm(instance=database_instance)

    return redirect(reverse('databases'))


@login_required
def show_sample_data(request):
    database = request.GET.get('database')
    table = request.GET.get('table')

    db = get_object_or_404(Database, id=database)
    conn = db.connect()
    cursor = conn.cursor()

    cursor.execute('select * from `%s` limit 20' % table)
    rows = cursor.fetchall()
    context = {
        'cursor': cursor
    }
    return render(request, 'dashboard/sample_data.html', context)
    # return HttpResponse(cursor.fetchall(), mimetype='text/plain')

analysis/core/templates/core/create_database.html
{% extends 'base.html' %}
{% load helper_tags %}

{% block sidebar %}
  {% include 'sidebar.html' with tab='database' %}
{% endblock %}

{% block title %} {% create_or_edit form.instance %}数据库 {% endblock %}
{% block content_header %} {% create_or_edit form.instance %}数据库 {% endblock %}

{% block content %}

  <div class="box box-primary">
    <form class="form-horizontal" action="" method="post">

      <div class="box-body">
        {% include 'form/horizontal_form.html' %}

        <div class="form-group">
          <label class="control-label col-sm-2 required" for="id_group">组：</label>

          <div class="col-sm-10">
            <select multiple="multiple" class="form-control" name="groups" id="id_groups" required>
              {% for group in all_groups %}
                <option value="{{ group.id }}" {% if group in form.instance.groups.all %}selected{% endif %}>{{ group }}</option>
              {% endfor %}
            </select>
            <span class="help-block"> 按下 "Control"，或者在Mac上按 "Command" 来选择多个值。 </span>
          </div>
        </div>
      </div>

      <div class="box-footer">
        <div class="col-sm-offset-2">
          <button class="btn btn-primary">保存</button>
        </div>
      </div>
    </form>
  </div>
{% endblock %}

analysis/core/templates/core/create_view.html
{% extends 'base.html' %}
{% load helper_tags %}

{% block title %} {% if not report %} 创建报表 {% else %} 修改报表 {% endif %} {% endblock %}
{% block content_header %} {% if not report %} 创建报表 {% else %} 修改报表 {% endif %} {% endblock %}

{% block sidebar %}
  {% render_sidebar 'data.view' %}
{% endblock %}

{% block body_class %} create-view {% endblock %}

{% block content %}

  <div class="box box-primary">
    <form class="form" method="post"
          action="{{ request.path }}"
          data-ng-app="sina" data-ng-controller="ViewController"
        >

      {% csrf_token %}

      <div class="box-body">

        <div class="form-group">
          <label class="control-label" for="id_database">数据库:</label>
          <select class="form-control" name="database"
                  required
                  ng-model="database"
                  ng-change="fetchTable()"
                  id="id_databases">

            {% for db in form.fields.database.queryset.all %}
              <option value="{{ db.id }}">{{ db }}</option>
            {% endfor %}
          </select>
        </div>

        {% verbatim %}

        <div class="form-group">
          <label class="control-label" for="id_table">表:</label>
          <select id="id_table" class="form-control"
                  required
                  ng-model="table"
                  ng-change="updateFields()"
                  ng-options="table.name for table in tables">
          </select>
          <input type="hidden" name="table" value="{{ table.name }}"/>
        </div>

        <div class="form-group" ng-show="table.name">
          <a class="btn btn-primary btn-xs" target="_blank"
             ng-href="{{ sample_data_url }}?database={{ database }}&table={{ table.name }}">查看数据</a>
        </div>

        <div class="form-group">
          <label class="control-label" for="id_name">报表名字:</label>
          <input class="form-control" type="text"
                 name="name" id="id_name"
                 required ng-model="name"
              />
        </div>

        <fieldset>
          <legend>字段列表</legend>

          <div ng-show="fields" class="row form-group">
            <div class="col-sm-2"> 字段名称  </div>
            <div class="col-sm-2"> 数据库字段 </div>
            <div class="col-sm-3"> 字段类型 </div>
            <div class="col-sm-2"> 数据类型 </div>
          </div>

          <div class="field-list" ui-sortable ng-model="fields">

          <div class="row form-group field-line" ng-repeat="field in fields">
            <div class="col-sm-2">
              <input class="form-control input-sm"  type="text"
                     ng-disabled="field.type == 'ignore'"
                     name="field_{{ $index }}_display" ng-model="field.display" />
            </div>

            <div class="col-sm-2">
              <select class="form-control input-sm"
                      ng-options="f.name as f.name for f in table.fields"
                      ng-model="field.source"
                      ng-hide="field.source == '$'"
                      ng-disabled="field.type == 'ignore'"
                  >
              </select>

              <input type="hidden" name="field_{{ $index }}_source" ng-value="field.source"/>
              <span ng-show="field.source == '$'"> 虚拟字段 </span>
            </div>

            <div class="col-sm-3">
              <div ng-hide="field.source == '$'">
                <label>
                  <input type="radio" name="field_{{ $index }}_type"
                         value='dimension'
                         ng-model="field.type" class="minimal" /> 维度
                </label>
                &nbsp;&nbsp;

                <label>
                  <input type="radio" name="field_{{ $index }}_type"
                         value='property'
                         ng-model="field.type" class="minimal" /> 指标
                </label>
                &nbsp;&nbsp;

                <label>
                  <input type="radio" name="field_{{ $index }}_type"
                         value='ignore'
                         ng-model="field.type" class="minimal" /> 忽略
                </label>
              </div>

              <div ng-show="field.source == '$'">
                <input type="text" name="field_{{ $index }}_expression"
                       class="form-control input-sm"
                       ng-model="field.expression"
                       placeholder="表达式: size * 1024 / time" />
              </div>
            </div>

            <div class="col-sm-2">
              <select name="field_{{ $index }}_data_type"
                      ng-if="field.type == 'dimension'"
                      ng-required="field.type == 'dimension'"
                      ng-model="field.data_type">

                <option value="char">字符串</option>
                <option value="datetime">日期和时间</option>
                <option value="date">日期 (不包含时间)</option>
                <option value="time">时间 (不包含日期)</option>
                <option value="province">省份</option>
              </select>

              <select name="field_{{ $index }}_data_type"
                      ng-if="field.type == 'property'"
                      ng-required="field.type == 'property'"
                      ng-model="field.data_type">

                <option value="number">数字</option>
                <option value="percent">百分比</option>
              </select>

              <!--
              <input type="text" placeholder="单位" ng-if="field.date_type == 'number'"/>
              -->

            </div>

            <div class="col-sm-1">
              <a> <i class="fa fa-arrows"></i> </a>
              &nbsp;
              <a href="" ng-click="fields.splice($index, 1)" title="删除字段">
                <i class="text-danger fa fa-trash-o"></i></a>
            </div>
          </div>
          </div>

          <input type="hidden" name="field_count" ng-value="fields.length" />

          <a class="btn btn-primary btn-xs" ng-click="addField()">
            <i class="fa fa-plus"></i> 虚拟字段
          </a>
        </fieldset>
        {% endverbatim %}
      </div>

      <div class="box-footer">
        <button class="btn btn-primary">保存</button>
      </div>
    </form>
  </div>

{% endblock %}

{% block extra_body %}
  <script src="{{ STATIC_URL }}js/angular.ui.sortable.js"></script>
  <script>
  var app = angular.module('sina', ['ui.sortable']);

  app.controller('ViewController', function($scope, $http){
    $scope.sample_data_url = "{% url 'get_sample_data' %}";

    /* 查询数据库的所有表格名字 */
    $scope.fetchTable = function(callback){
      var db = $scope.database;
      if ( !db ) {
        return;
      }

      $http.get('{% url "query_tables" %}?database=' + db).
          success(function(tables, status){
            $scope.tables = tables;
            if (callback) {
              callback();
            }

          });
    };

    // 添加一个虚拟字段
    $scope.addField = function(){
      $scope.fields.push({
        display: '',
        type: 'property',
        source: '$',
        data_type: 'number'
      })
    };

    function guessField(field) {
      var displays = {
        isp: '运营商',
        province: '省份',
        sip: '服务器',
        server: '服务器',
        cluster: '集群',
        requests: '请求数',
        hits: '命中',
        time: '时间',
        duration: '时长',
        size: '大小',
        date: '日期',
        traffic: '流量'
      };

      var result = {
        display: displays[field.name] || field.name,
        source: field.name,
        type: 'ignore',
        data_type: 'number',
        expression: ''
      };

      if (field.name === 'id') {
        result['type'] = 'ignore';

      } else if (/int/.test(field.type)) {
        result['type'] = 'property';

      } else {
        result.type = 'dimension';
        result.data_type = 'char';

        if (field.type === 'date') {
          result.data_type = 'date';
        } else if (field.type === 'time') {
          result.data_type = 'time';
        } else if (field.type === 'datetime') {
          result.data_type = 'datetime';
        } else if (field.name === 'province') {
          result.data_type = 'province';
        }
      }

      return result;
    };

    $scope.updateFields = function(callback){
      if ( !$scope.table ) {
        return;
      }

      if ( callback ) {
        callback();

      } else {
        $scope.fields = $scope.table.fields.map(function(field){
          return guessField(field);
        });

      }
    };

    {% if report %}
      // 如果是编辑视图，则初始化一部分数据
      $scope.database = {{ report.database_id }};
      $scope.name = '{{ report.name }}';
      $scope.fields = [];

      {% for field in report.fields.all %}
        $scope.fields.push({
          display: '{{ field.display }}',
          source: '{{ field.source }}',
          type: '{{ field.type_string }}',
          data_type: '{{ field.data_type }}',
          expression: '{{ field.expression }}'
        });
      {% endfor %}

      $scope.fetchTable(function(){
        var tables = $scope.tables;
        for( var i in tables){
          if (tables[i].name === '{{ report.table }}') {
            $scope.table = tables[i];

            var exiting = $scope.fields.map(function(f){
              return f.source;
            });

            $scope.table.fields.map(function(field){
              if ( exiting.indexOf(field.name) === -1 ) {
                var f = guessField(field);
                f.type = 'ignore';
                $scope.fields.push(f);
              }
            });
            break;
          }
        }
      });

    {% elif form.initial.database %}
      $scope.database = {{ form.initial.database }};
      $scope.fetchTable();

    {% endif %}
  });
  </script>
{% endblock %}

analysis/core/templates/core/database_group.html
{% extends 'base.html' %}

{% block sidebar %}
  {% include 'sidebar.html' with tab='database' %}
{% endblock %}

{% block title %} 数据库{{ database.id }}用户组管理 {% endblock %}
{% block content_header %} 数据库{{ database.name }} 用户组 {% endblock %}
{% load helper_tags %}

{% block content %}
  <div class="box box-primary">
    <form action="{%url 'manage_database_group' database.id %}" method="post">
        {% csrf_token %}

        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span>
            <span class="sr-only">Close</span></button>

          <h4 class="modal-title">{{database.name}}-用户组管理</h4>
        </div>

        <div class="modal-body">
          {% get_dbgroup_form database %}
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button class="btn btn-primary" ng-disabled="databaseForm.$invalid">Save</button>
        </div>
      </form>
  </div>
{% endblock %}

analysis/core/templates/core/manage_databases.html
{% extends 'theme_base.html' %}
{% load helper_tags %}
{% load pagination_tags %}

{% block title %} 管理数据库 {% endblock %}
{% block content_header %} 数据库 {% endblock %}

{% block sidebar %}
{% render_sidebar 'data.database' %}
{% endblock %}

{% block content %}
{% autopaginate databases %}

<table class="table table-bordered">
  <thead>
  <tr>
    <th>数据库</th>
    <th>类型</th>
    <th>主机</th>
    <th>端口</th>
    <th>用户名</th>
    <th>用户组</th>
    <th>创建人</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  {% for db in databases %}
  <tr>
    <td>{{ db.name }}</td>
    <td>{{ db.get_engine_display }}</td>
    <td>{{ db.host }}</td>
    <td>{{ db.port }}</td>
    <td>{{ db.user }}</td>
    <td>
      <a href="#manage_database_group-{{ db.id }}" data-toggle="modal"
         class="pull-right"
         title="用户组管理">
        <i class="fa fa-edit"></i>
      </a>
      <ul>
        {% for group in db.groups.all %}
          <li>
            {{ group.name }}
          </li>
        {% empty %}
          <li>
            没有用户组
          </li>
        {% endfor %}
      </ul>
    </td>

    <td>{{ db.creator }}</td>

    <td>
      <div class="btn-toolbar ">
        <div class="btn-group btn-group-sm">

          <a class="btn btn-default" href="{% url 'edit_database' db.id %}"
             title="编辑数据库">
            <i class="fa fa-pencil"></i>
          </a>

          <a class="btn btn-default" href="{% url 'create_view' %}?db={{ db.id }}"
             title="创建数据视图">
            <i class="fa fa-bar-chart-o"></i>
          </a>

          <a class="btn btn-default" href="{% url 'create_job' %}?db={{ db.id }}"
             title="创建导入程序">
            <i class="fa fa-truck"></i>
          </a>
          <a class="post-link btn btn-danger" href="{% url 'delete_database' db.id %}"
             title="删除数据库"
             data-confirm="确认删除？">
            <i class="fa fa-trash-o"></i>
          </a>
        </div>
      </div>
    </td>
  </tr>
  {% endfor %}

  </tbody>
</table>
{% paginate %}

<p>
  <a class="btn btn-primary" href="#create-modal" data-toggle="modal">添加新的</a>
</p>


<div class="modal fade" id="create-modal">
  <div class="modal-dialog">
    <div class="modal-content">

      <form action="{% url 'create_database' %}" method="post" name="databaseForm">
        {% csrf_token %}

        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span>
            <span class="sr-only">Close</span></button>

          <h4 class="modal-title">创建数据库</h4>
        </div>

        <div class="modal-body">
          <div class="form-group">
            <label class="control-label" for="id_host">主机：</label>
            <input class="form-control" type="text" name="host" placeholder="10.23.22.33" required/>
          </div>

          <div class="form-group">
            <label class="control-label" for="id_port">端口：</label>
            <input class="form-control" type="number" name="port" value="3306" required/>
          </div>

          <div class="form-group">
            <label class="control-label" for="id_name">数据库：</label>
            <input class="form-control" type="text" name="name" required/>
          </div>

          <div class="form-group">
            <label class="control-label" for="id_name">用户名：</label>
            <input class="form-control" type="text" name="user" required/>
          </div>

          <div class="form-group">
            <label class="control-label" for="id_name">密码：</label>
            <input class="form-control" type="password" name="password"/>
          </div>


          <div class="form-group">
            <label class="control-label" for="id_group">组：</label>
            <select multiple="multiple" class="form-control" name="groups" id="id_groups" required>
              {% for group in groups %}
                <option value="{{ group.id }}">{{ group.name }}</option>
              {% endfor %}
            </select>
            <span class="help-block"> 按下 "Control"，或者在Mac上按 "Command" 来选择多个值。 </span>
          </div>

        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button class="btn btn-primary" ng-disabled="databaseForm.$invalid">Save</button>
        </div>
      </form>

    </div>
  </div>
</div>

{% for db in databases %}
<div class="modal fade" id="manage_database_group-{{db.id}}">
  <div class="modal-dialog">
    <div class="modal-content">
      <form action="{%url 'manage_database_group' db.id %}" method="post" name="dbGroupForm{{db.id}}">
        {% csrf_token %}

        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span>
            <span class="sr-only">Close</span></button>
          <h4 class="modal-title">{{ db.name }} 用户组管理</h4>
        </div>

        <div class="modal-body">
          {% get_dbgroup_form db %}
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button class="btn btn-primary" ng-disabled="databaseForm.$invalid">Save</button>
        </div>
      </form>

    </div>
  </div>
</div>
    {% endfor %}
{% endblock %}