analysis/collection/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'analysis.collection.views',
    url(r'^star$', 'star_report', name='star_report'),
    url(r'^list$', 'list_collection', name='list_collection'),
    url(r'^create$', 'create_collection', name='create_collection'),
    url(r'^create/(\d+)$', 'create_collection', name='edit_collection'),
    url(r'^create/report$', 'create_report', name='create_report'),
    url(r'^delete/(\d+)$', 'delete_collection', name='delete_collection'),
    url(r'^feature/(\d+)$', 'feature_collection', name='feature_collection'),
    url(r'^detail/(\d+)$', 'show_collection_detail', name='collection_detail'),

    url(r'^widget/report/change_size$', 'change_report_size', name='change_report_size'),

    url(r'^(\d+)$', 'collection_report', name='collection_report'),

    url(r'^(\d+)/sort$', 'sort_widgets', name='sort_widgets'),
    url(r'^widget/(\d+)/remove$', 'remove_widget', name='remove_widget'),
    url(r'link$', 'list_external_links', name='list_external_links'),
    url(r'link/create$', 'create_link', name='create_links'),
    url(r'link/edit/(\d+)$', 'create_link', name='edit_link'),
    url(r'link/(\d+)$', 'show_link', name='show_link'),
    url(r'link/delete/(\d+)$', 'delete_link', name='delete_link'),
    url(r'collection/group/(\d+)', 'list_collection_link_for_group', name='list_group_collections')
)

analysis/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', 'analysis.dashboard.views.home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('analysis.account.urls')),

    url(r'^dashboard/collection/', include('analysis.collection.urls')),
    url(r'^dashboard/', include('analysis.dashboard.urls')),

    url(r'^manage/', include('analysis.dip.urls')),
    url(r'^manage/aggregate/', include('analysis.aggregate.urls')),
    url(r'^manage/', include('analysis.core.urls')),
)

analysis/collection/models.py
# coding: utf8
from __future__ import unicode_literals
from django.contrib.auth.models import User, Group
from django.db import models
from django.db.models import Q
from django.utils import timezone


class CollectionManager(models.Manager):
    def for_user(self, user):
        return self.filter(
            Q(creator=user) | Q(group__in=user.groups.all())
        ).order_by('group')


class Collection(models.Model):
    """
    报表集合
    """
    creator = models.ForeignKey(User)
    group = models.ForeignKey(Group, null=True, blank=True)
    name = models.CharField(max_length=100)
    is_featured = models.BooleanField(default=False)
    create_at = models.DateTimeField(default=timezone.now)

    objects = CollectionManager()

    def __unicode__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return 'collection_detail', [self.id]


class ReportType:
    """
    数据集类型，包括:
    表格
    外链
    图形
    """
    IFRAME = 0
    TABLE = 1
    GRAPHIC = 2


class Report(models.Model):
    """
    数据集
    """
    creator = models.ForeignKey(User, related_name='reports')
    collection = models.ForeignKey(Collection, related_name='reports')

    name = models.CharField(max_length=100)
    url = models.CharField(max_length=200)
    type = models.SmallIntegerField()

    order = models.PositiveIntegerField(default=0)
    width = models.PositiveIntegerField(default=400)
    height = models.PositiveIntegerField(default=300)

    create_at = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['order']

    def __unicode__(self):
        return self.name


class Link(models.Model):
    """
    外部链接
    """
    creator = models.ForeignKey(User, related_name="links")
    group = models.ForeignKey(Group, null=True, blank=True)
    name = models.CharField(max_length=100)
    url = models.URLField()

    created_at = models.DateTimeField(default=timezone.now)

    def __unicode__(self):
        return self.name

analysis/collection/forms.py
#coding: utf-8
from django import forms
from analysis.collection.models import Collection, Report, Link


class CollectionForm(forms.ModelForm):
    class Meta:
        model = Collection
        fields = ('creator', 'name', 'group')

    def clean(self):
        cleaned_data = super(CollectionForm, self).clean()

        name = cleaned_data.get('name')
        creator = cleaned_data.get('creator')

        if Collection.objects.filter(creator=creator, name=name).exists():
            raise forms.ValidationError("已经存在此集合！")

        if name.lower() == 'dashboard':
            raise forms.ValidationError("不能使用Dashboard为集合名称")

        return cleaned_data


class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ('name', 'collection', 'url', 'creator')

    url = forms.URLField()

class LinkForm(forms.ModelForm):
    class Meta:
        model = Link
        fields = ('name', 'url', 'group')

        widgets = {
            'group': forms.Select()
        }
    url = forms.URLField()

analysis/collection/views.py
# coding: utf8
from __future__ import unicode_literals

import json
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.db.models.query_utils import Q
from django.shortcuts import render, get_object_or_404, redirect
from analysis.account.utils import in_group
from analysis.collection.models import Report, Collection, ReportType, Link
from analysis.core.utils import render_json

from django.contrib import messages
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.http import HttpResponse, Http404

from django.views.decorators.http import require_POST
from analysis.collection.forms import CollectionForm, ReportForm, LinkForm


@login_required
def show_collection_detail(request, collection_id):
    '''
    :param request:
    :param collection_id:
    :return:detail of a collection
    '''
    collection = get_object_or_404(Collection, id=collection_id)
    reports = Report.objects.filter(collection=collection).select_related('creator')
    context = {
        'collection': collection,
        'reports': reports
    }
    return render(request, 'collection/collection_detail.html', context)


@login_required
def list_collection(request):
    """
    列出所有用户和用户所在组的收藏夹
    """

    collections = Collection.objects.for_user(request.user)
    user_groups = request.user.groups.all()

    context = {
        'collections': collections,
        'user': request.user,
        'user_groups': user_groups
    }

    return render(request, 'collection/list_collections.html', context)

@login_required
def list_collection_link_for_group(request, group_id):
    """
    列出所有用户和用户所在组的收藏夹
    """
    group = get_object_or_404(Group, id=group_id)
    collections = Collection.objects.filter(group=group)
    links = Link.objects.filter(group=group)

    context = {
        'group': group,
        'collections': collections,
        'links': links
    }

    return render(request, 'list_group_collections.html', context)


def create_collection(request, collection_id=None):
    instance = get_object_or_404(Collection, id=collection_id) if collection_id else None

    if request.method == 'POST':
        form = CollectionForm(request.POST, instance=instance)
        try:
            if form.is_valid():
                # 判断自己是否已经创建该收藏夹
                collection = form.save(commit=False)
                if collection.creator != request.user:
                    raise ValidationError(u'用户无权创建此收藏夹!')
                if instance and instance.creator != request.user:
                    raise ValidationError("您没有权限修改或创建该收藏夹!")
                messages.success(request, "收藏夹创建成功！")
                collection.save()
            else:
                error_message = []
                for (k,v) in form.errors.items():
                    error_message += v
                messages.error(request, '\n'.join(error_message))
        except ValidationError, e:
            messages.error(request, '\n'.join(e.messages))
        finally:
            return redirect(reverse("list_collection"))
    else:
        form = CollectionForm(instance=instance)
        return render(request, '', {'form': form})


@require_POST
@login_required
def feature_collection(request, collection_id):
    collection = get_object_or_404(Collection, id=collection_id)
    if collection.is_featured:
        collection.is_featured = False
    else:
        collection.is_featured = True
    collection.save()
    return redirect(reverse('list_collection'))

@require_POST
@login_required
def delete_collection(request,collection_id):
    collection = get_object_or_404(Collection, id=collection_id)
    if request.user.id != collection.creator.id:
        messages.error(request, "您没有权限删除此收藏夹！")
    else:
        collection.delete()
        messages.success(request, "收藏夹删除成功！")
    return redirect(reverse('list_collection'))


def create_report(request, report_id=None):
    instance = get_object_or_404(Report, id=report_id) if report_id else None

    if request.method == 'POST':
        form = ReportForm(request.POST, instance=instance)
        collection_id = request.POST.get('collection')
        try:
            if form.is_valid():
                report = form.save(commit=False)

                creator = form.cleaned_data.get('creator')
                if creator != request.user:
                    raise ValidationError("您没有权限修改或创建该收藏夹!")
                if instance and instance.creator != request.user:
                    raise ValidationError("您没有权限修改或创建该收藏夹!")
                report.type = ReportType.IFRAME
                report.save()
                if report_id:
                    messages.success(request, "编辑外部报表成功！")
                else:
                    messages.success(request, "新建外部报表成功！")
            else:
                error_message = []
                for (k,v) in form.errors.items():
                    error_message += v
                messages.error(request, '\n'.join(error_message))

        except ValidationError, e:
            messages.error(request, '\n'.join(e.messages))
        finally:
            return redirect(reverse('collection_detail', args=(collection_id,)))
    else:
        form = ReportForm(instance=instance)
        return render(request, '', {'form': form})


@login_required
def star_report(request):
    url = request.POST.get('url')
    cid = request.POST.get('collection')
    name = request.POST.get('name')
    type = request.POST.get('type')

    if not cid:
        collection, created = Collection.objects.get_or_create(
            creator=request.user, name='Dashboard',
        )

    else:
        #TODO: 检查用户是否有这个 Collection 的权限
        collection = get_object_or_404(Collection, id=cid)

    Report.objects.create(
        creator=request.user,
        collection=collection,
        name=name, url=url,
        type=ReportType.TABLE if type == 'table' else ReportType.GRAPHIC,
    )

    return redirect(request.META.get('HTTP_REFERER'))
    # return render_json({'success': True})


@login_required
def collection_report(request, cid):
    collection = get_object_or_404(Collection, id=cid)

    if not Collection.objects.for_user(request.user).filter(id=cid).exists():
        messages.error(request, "您无权查看此收藏夹")

    context = {
        'collection': collection,
        'ReportType': ReportType
    }
    return render(request, "collection/collection_report.html", context)


@require_POST
@login_required
def change_report_size(request):
    report_id = request.POST.get('report', '')
    width = request.POST.get('width', '')
    height = request.POST.get('height', '')

    if not report_id.isdigit() or not width.isdigit() or not height.isdigit():
        return HttpResponse(status=400)

    report = get_object_or_404(Report, id=report_id)
    if report.creator_id == request.user.id or in_group(request.user, report.collection.group):
        report.width = abs(int(width))
        report.height = abs(int(height))
        report.save()

        return render_json({'success': True})

    return render_json({'success': False, 'error': '没有权限'})


@require_POST
@login_required
def sort_widgets(request, collection_id):
    collection = get_object_or_404(Collection, id=collection_id)
    sorted_ids = request.POST.get('sorted', '').split(',')
    reports = dict((report.id, report) for report in collection.reports.all())

    for idx, report_id in enumerate(sorted_ids):
        report = reports[int(report_id)]
        report.order = idx
        report.save()

    return render_json({'success': True})


@require_POST
@login_required
def remove_widget(request, wid):
    widget = get_object_or_404(Report, id=wid)

    if widget.creator_id == request.user.id or in_group(request.user, widget.collection.group):
        widget.delete()

        return render_json({'success': True})

    return render_json({'success': False, 'error': '您没有权限删除此挂件'})


@login_required
def list_external_links(request):
    user_links = Link.objects.filter(
        Q(creator=request.user) | Q(group__in=request.user.groups.all())
    ).order_by('group')

    return render(request,
                  'external/list_external_links.html',
                  {'external_links': user_links})

@login_required
def create_link(request, link_id=None):
    instance = get_object_or_404(Link, id=link_id) if link_id else None
    if request.method == 'POST':
        form = LinkForm(request.POST, instance=instance)

        if form.is_valid():
            # 判断自己是否已经创建该收藏夹
            link = form.save(commit=False)
            if instance:
                if instance.creator != request.user:
                    raise ValidationError("您没有权限修改或创建该外部链接!")
            else:
                link.creator = request.user

            link.save()
            messages.success(request, "外部链接创建成功！")
            return redirect(reverse("list_external_links"))
        else:
            messages.error(request, form.errors)
    else:
        form = LinkForm(request.POST, instance=instance)
        return render(request, 'external/create_link.html', {'form': form})

@login_required
def show_link(request, id):
    link = get_object_or_404(Link, id=id)
    return render(request, 'external/link_detail.html', {'link': link})


@require_POST
@login_required
def delete_link(request, id):
    link = get_object_or_404(Link, id=id)

    if link.creator == request.user:
        link.delete()
        messages.success(request,"%s删除成功！" % link.name)

    else:
        messages.error(request,"没有权限删除链接-%s" % link.name)
    return redirect(request.META.get('HTTP_REFERER'))

analysis/collection/templates/collection/ceate_dataset_collection.html
{% extends 'base.html' %}
{% load helper_tags pagination_tags %}

{% block title %} {{ title }} {% endblock %}
{% block content %}
{#  显示form #}
  <div class="box box-primary">
    <form class="form-horizontal" action="" method="post">

      <div class="box-body">
        {% include 'form/horizontal_form.html' %}
      </div>

      <div class="box-footer">
        <div class="col-sm-offset-2">
          <button class="btn btn-primary">保存</button>
        </div>
      </div>
    </form>
  </div>
{% endblock %}

analysis/collection/templates/collection/collection_detail.html
{% extends 'base.html' %}
{% load helper_tags %}
{% load collection_tags %}
{% load pagination_tags %}

{% block title %} 收藏夹-{{ collection.name }}-详情 {% endblock %}
{% block content_header %} 收藏夹-{{ collection.name }}-详情 {% endblock %}

{% block sidebar %}
  {% render_sidebar 'data.collection' %}
{% endblock %}

{% block content %}

{% autopaginate reports %}
<table class="table table-bordered">
  <caption>收藏夹-{{ collection.name }}-详情</caption>
  <thead>
  <tr>
    <th>报表名称</th>
    <th>创建人</th>
    <th>收藏夹</th>
    <th>url</th>
    <th>类型</th>
    <th>创建时间</th>
  </tr>
  </thead>
  <tbody>
  <!-- 分页显示report -->
  {% for report in reports %}
    <tr>
      <td>{{ report.name }}</td>
      <td>{{ report.creator.username }}</td>
      <td>{{ report.collection }}</td>
      <td>{{ report.url }}</td>
      <td>{{ report.type }}</td>
      <td>{{ report.create_at|date:'Y年m月d日 H:i' }}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% paginate %}

<p>
  <a class="btn btn-primary" href="#create-outreport" data-toggle="modal">创建外部报表</a>
</p>


<div class="modal fade" id="create-outreport">
  <!-- 创建外部报表 -->
  <div class="modal-dialog">
    <div class="modal-content">

      <form action="{% url 'create_report' %}" method="post" name="reportForm">
        {% csrf_token %}

        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span>
            <span class="sr-only">Close</span></button>

          <h4 class="modal-title">创建外部报表</h4>
        </div>

        <div class="modal-body">
          <input name="creator" value="{{ collection.creator.id }}" type="hidden">
          <div class="form-group">
            <label class="control-label" for="id_name">报表名称：</label>
            <input class="form-control" type="text" name="name" placeholder="名称" required/>
          </div>

          <div class="form-group">
            <label class="control-label" for="id_url">url:</label>
            <input class="form-control" type="url" name="url" placeholder="http://" required>
          </div>

          <input type="hidden" name="collection" value="{{ collection.id }}"/>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button class="btn btn-primary" ng-disabled="reportForm.$invalid">Save</button>
        </div>
      </form>

    </div>
  </div>
</div>
{% endblock %}

analysis/collection/templates/collection/collection_report.html
{% extends 'base.html' %}

{% block title %} {{ collection }} {% endblock %}

{% block body_class %} collection-report {% endblock %}
{% block sidebar %}
  {% include "sidebar.html" with section='collection' tab=collection.id %}
{% endblock %}

{% block extra_head %}
{#  <link rel="stylesheet" href="{{ STATIC_URL }}gridster/jquery.gridster.min.css"/>#}
{% endblock %}

{% block content %}
  <style>
  .content{padding: 0px; background:#333;}
  </style>

  <div ng-app="sina" id='widgets-container'>
    <div id="widgets" class="gridly">
      {% include 'collection/collection_report_snippet.html' with reports=collection.reports.all %}
    </div>
  </div>
{% endblock %}

{% block extra_body %}
  <link rel="stylesheet" href="{{ STATIC_URL }}jquery.gridly/stylesheets/jquery.gridly.css"/>
  <script type="text/javascript" src="{{ STATIC_URL }}js/vendor/moment-with-langs.min.js"></script>
  <script src="{{ STATIC_URL }}jquery.gridly/javascripts/jquery.gridly.js?v=2"></script>
  <script>
  $(function(){
    var widgets = $('#widgets');

    $('.report-box').resizable({
      grid: [80, 40],
      resize: function(event, ui){
      },
      stop: function(event, ui){
        var id = ui.element.attr('data-id');
        var req = $.post('{% url "change_report_size" %}', {
          csrfmiddlewaretoken: '{{ csrf_token }}',
          report: id,
          width: ui.size.width,
          height: ui.size.height

        }, function(json){
          console.log('finished change report size');
        }, 'json');

        setTimeout(function () {
          widgets.gridly('layout');
        }, 200);
      }
    });

    widgets.gridly({
      base: 20,
      gutter: 20,
      columns: 25,
      draggable: {
        selector: '.widget',
        holder: '.widget .box-header'
      },
      callbacks: {
        reordered: function (elements) {
          elements = $.makeArray(elements);

          var ids = elements.map(function (ele, idx) {
            return ele.attributes['data-id'].value;
          });
          console.log(ids);
          $.post("{% url 'sort_widgets' collection.id %}", {
            csrfmiddlewaretoken: '{{ csrf_token }}',
            sorted: ids.join(',')
          }, function (json) {
            console.log('sorted success');
          });
        }
      }
    });

    $(document).on('click', '.remove-widget', function(event){
      event.preventDefault();

      if (confirm("确定要删除吗?")) {
        var url = this.href;
        var container = $(this).closest('.report-box');
        widgets.gridly('layout');

        $.post(url, {
          csrfmiddlewaretoken: '{{ csrf_token }}'
        }, function(json){
          if ( json.success ) {
            container.fadeOut(function(){
              container.remove(); widgets.gridly('layout');
            });
          }
        }, 'json')
      }
    });

    $('.widget iframe').load(function(){
      console.log('iframe loaded:', this.src);
      var iframe = this;
      setTimeout(function(){
        iframe.src = iframe.src;
      }, 1000 * 60);
    });
  })
  </script>

  <script src="{{ STATIC_URL }}graph/echarts-plain-map.js"></script>
  <script src="{{ STATIC_URL }}graph/libgraph.js"></script>
  <script>
    var app = angular.module('sina', []);
    app.directive('test', function () {
      return {
        restrict: 'E',
        template: 'test'
      }
    });
  </script>
  <script src="{{ STATIC_URL }}js/view.js?v=6"></script>
{% endblock %}

analysis/collection/templates/collection/collection_report_snippet.html
{% load helper_tags %}
{% for report in reports %}

  <div class="box box-solid report-box widget"
       data-id="{{ report.id }}"
       style="width: {{ report.width }}px; height: {{ report.height }}px;"
      >

    <div class="box-header bg-black">
      <div class="box-title">{{ report }}</div>
      <div class="pull-right">
        <a target="_blank" href="{{ report.url|parse_relative_date|safe }}">
          <i class="fa fa-external-link"></i>
        </a>
        <a class="remove-widget"
           href='{% url "remove_widget" report.id %}'
           ><i class="fa fa-times"></i>
          &nbsp;
        </a>
      </div>
    </div>

    <div class="box-body">

      {% if report.type == ReportType.GRAPHIC %}
        <graph title="'{{ report.name }}'"
               url='"{{ report.url|parse_relative_date|safe }}"'
               type='"{{ report.get_type_display }}"'
               style="height: 400px;width: 300px;"
               show='true'
               refresh="60000"
            >
        </graph>

      {% elif report.type == ReportType.TABLE %}

        <report title="'{{ report.name }}'" url='"{{ report.url|safe }}"'
                show="true"
                refresh="60000">
        </report>

      {% elif report.type == ReportType.IFRAME %}
        <iframe src="{{ report.url|safe }}" frameborder="0"></iframe>

      {% endif %}
    </div>
  </div>
{% endfor %}

analysis/collection/templates/collection/list_collections.html
{% extends 'base.html' %}
{% load helper_tags %}
{% load pagination_tags %}

{% block title %} 收藏夹管理 {% endblock %}
{% block content_header %} 收藏夹 {% endblock %}

{% block sidebar %}
{% render_sidebar 'data.collection' %}
{% endblock %}

{% block content %}
{% autopaginate collections %}

<table class="table table-bordered">
  <caption>收藏夹</caption>
  <thead>
  <tr>
    <th>名称</th>
    <th>创建时间</th>
    <th>操作</th>
  </tr>
  </thead>
  <tbody>
  {% for collection in collections %}
    <tr>
      <td>
        <a href="{{ collection.get_absolute_url }}">

          {% if collection.group == None %}
             <span>{{ collection.name }}</span> <i class="fa fa-lock pull-right"></i>

          {% else %}
            <span>{{ collection.group.name }}/{{ collection.name }}</span>
          {% endif %}

        </a>
      </td>

      <td>{{ collection.create_at|date:'Y/m/d H:i' }}</td>
      <td>
{#        <div class="btn-group btn-group-xs">#}
{#          <a title="推荐"#}
{#             class="post-link btn btn-default"#}
{#             href="{% url 'feature_collection' collection.id %}"#}
{#              {% if collection.is_featured %}#}
{#             data-confirm="取消推荐此收藏夹？"#}
{#              {% else %}#}
{#             data-confirm="确定推荐此收藏夹？"#}
{#              {% endif %}>#}
{#            {% if collection.is_featured %}#}
{#            <i class="glyphicon glyphicon-star text-yellow"></i>#}
{#            {% else %}#}
{#            <i class="glyphicon glyphicon-star-empty"></i>#}
{#            {% endif %}#}
{##}
{#          </a>#}
          <a class="post-link btn btn-sm btn-danger" href="{% url 'delete_collection' collection.id %}"
            data-confirm="删除收藏夹后，收藏夹内的报表也会被删除。确定删除？" title="删除收藏夹">
            <i class="fa fa-trash-o"></i>
          </a>
{#        </div>#}
      </td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% paginate %}

<p>
  <a class="btn btn-primary" href="#create-collection" data-toggle="modal">创建收藏夹</a>
</p>


<div class="modal fade" id="create-collection">
  <div class="modal-dialog">
    <div class="modal-content">

      <form action="{% url 'create_collection' %}" method="post" name="collectionForm">
        {% csrf_token %}

        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span>
            <span class="sr-only">Close</span></button>

          <h4 class="modal-title">创建收藏夹</h4>
        </div>

        <div class="modal-body">
          <input type="hidden" name="creator" value="{{ user.id }}"/>
          <div class="form-group">
            <label class="control-label" for="id_name">收藏夹名称：</label>
            <input class="form-control" type="text" name="name" placeholder="名称,名称不能为Dashboard" required/>
          </div>

          <div class="form-group">
            <label class="control-label" for="id_group">属于：</label>
            <select name="group" id="id_group" class="form-control">
              <option value="">私有</option>
              <optgroup label="组">
                {% for group in user_groups %}
                  <option value="{{ group.id }}">{{ group.name }}</option>
                {% endfor %}
              </optgroup>
            </select>
          </div>

        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button class="btn btn-primary" ng-disabled="collectionForm.$invalid">Save</button>
        </div>
      </form>

    </div>
  </div>
</div>
{% endblock %}